- name: deploy, enable scaling
  hosts: localhost
  user: ubuntu
  become: yes

  vars:
    myPath: “/home/ubuntu/”

  tasks:
 
  - name: Update Package Manager
    apt:
      update_cache: yes

  - name: Create Deployment
    become: no
    shell:
      cmd: kubectl create deployment devopscw2 --image=docker.io/emmag500/server_app:1.0

  - name: Create Service
    become: no
    shell:
      cmd: kubectl expose deployment/devopscw2 --type="NodePort" --port 8080 --name node-port-service

  - name: Scale Deployments
    become: no
    shell:
      cmd: kubectl scale deployments/devopscw2 --replicas=4
